# Generated by Django 4.2.1 on 2023-05-25 12:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('idNum', models.IntegerField()),
                ('nombre', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('cvv', models.IntegerField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('sede', models.CharField(choices=[('Barranquilla', 'Barranquilla'), ('Cartagena', 'Cartagena'), ('Santa Marta', 'Santa Marta'), ('Sincelejo', 'Sincelejo'), ('Monteria', 'Monteria')], default='Barranquilla', max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('cuotas', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
